# Uncomment the next line to define a global platform for your project
platform :ios, '14.7'

target 'Trashsure' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Trashsure
  pod 'SnapKit', '~> 5.0.0'

  target 'TrashsureTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'TrashsureUITests' do
    # Pods for testing
  end

end
